module.exports = {
  // Vehicle
  ADD_VEHICLE: "ADD_VEHICLE",
  UPDATE_VEHICLE: "UPDATE_VEHICLE",
  DELETE_VEHICLE: "DELETE_VEHICLE",
  UPDATE_VEHICLE_GROUP: "UPDATE_VEHICLE_GROUP",

  // Booking
  CREATE_BOOKING: "CREATE_BOOKING",
  CANCEL_BOOKING: "CANCEL_BOOKING",
  COMPLETE_BOOKING: "COMPLETE_BOOKING",
  RESCHEDULE_BOOKING: "RESCHEDULE_BOOKING",

  // User / Admin
  LOGIN: "LOGIN",
  ROLE_CHANGE: "ROLE_CHANGE"
};
