version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - RABBITMQURL=amqp://admin:admin123@rabbitmq:5672
      - DLQ_NAME=emailDLQ
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - SENDER_MAIL_ID=25rohitkumar98@gmail.com
      - MAIL_PASS=glearzefyijihhql
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

  consumer:
    build: ./messageServices
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RABBITMQURL=amqp://admin:admin123@rabbitmq:5672
      - DLQ_NAME=emailDLQ
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - SENDER_MAIL_ID=25rohitkumar98@gmail.com
      - MAIL_PASS=glearzefyijihhql
      - BACKEND_SERVICE_URL=http://backend:5000/createnotification
    depends_on:
      - rabbitmq
      - backend

