version: "3.9"
services:
  # ---------- 1️⃣ RabbitMQ ----------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    ports:
      - "5672:5672"     # Main AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    restart: always

  # ---------- 2️⃣ Node.js Backend ----------
  backend:
    build:
      context: ./backend        # Folder containing backend Dockerfile
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always

  # ---------- 3️⃣ React Frontend ----------
  frontend:
    build:
      context: ./frontend       # Folder containing frontend Dockerfile
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000"               # Serve React build on port 3000
    depends_on:
      - backend
    restart: always
